#pragma warning disable 1591
#pragma warning disable 0108

#region License
// Copyright 2012 Hedgehog Development, LLC (www.hhogdev.com)
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//	   http://TeamDevelopmentForSitecore.com
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using HedgehogDevelopment.Scaas.Content;
using HedgehogDevelopment.Scaas.Content.Fields;

namespace HedgehogDevelopment.Scaas.Models
{
	/// <summary>
	///	Service
	///	<para></para>
	///	<para>Path: /sitecore/templates/HedgehogDevelopment/Scaas/Models/Service</para>	
	///	<para>ID: 025a21e2-d6c7-4d9e-bae0-990f1c658dd3</para>	
	///	<remarks>Generated by Team Development for Sitecore</remarks>
	///	</summary>
	public partial class ServiceItem : HedgehogDevelopment.Scaas.Content.ContentItem
	{
	
	}
}


namespace HedgehogDevelopment.Scaas.Models
{
	/// <summary>
	///	Promotions
	///	<para></para>
	///	<para>Path: /sitecore/templates/HedgehogDevelopment/Scaas/Models/Promotions</para>	
	///	<para>ID: 0cf45b0e-a623-4061-b791-203961b23a19</para>	
	///	<remarks>Generated by Team Development for Sitecore</remarks>
	///	</summary>
	public partial class PromotionsItem : HedgehogDevelopment.Scaas.Content.ContentItem
	{
		/// <summary>
		///	The PromotionCopy field.
		///	<para></para>
		///	<para>Field Type: Rich Text</para>		
		///	<para>Field ID: 179c1f99-9308-4a30-a93c-1cf1c5329edb</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public string PromotionCopy  {get; set;}

		/// <summary>
		///	The PromotionImage field.
		///	<para></para>
		///	<para>Field Type: Image</para>		
		///	<para>Field ID: b5239638-bf16-4098-ade7-fd468670aacf</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public ImageField PromotionImage  {get; set;}

		/// <summary>
		///	The PromotionTitle field.
		///	<para></para>
		///	<para>Field Type: Single-Line Text</para>		
		///	<para>Field ID: 08c53b4c-4e72-42fd-b60b-80c26e0d9d50</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public string PromotionTitle  {get; set;}

		/// <summary>
		///	The PromotionUrl field.
		///	<para></para>
		///	<para>Field Type: General Link</para>		
		///	<para>Field ID: a7c39e1a-4479-4362-afe9-9b01d940437a</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public LinkField PromotionUrl  {get; set;}

	
	}
}


namespace HedgehogDevelopment.Scaas.Models
{
	/// <summary>
	///	ArticleFolder
	///	<para></para>
	///	<para>Path: /sitecore/templates/HedgehogDevelopment/Scaas/Models/ArticleFolder</para>	
	///	<para>ID: 5b11c8f9-4e8e-4f4c-a455-daa53eeafb7e</para>	
	///	<remarks>Generated by Team Development for Sitecore</remarks>
	///	</summary>
	public partial class ArticleFolderItem : HedgehogDevelopment.Scaas.Content.ContentItem
	{
	
	}
}


namespace HedgehogDevelopment.Scaas.Models
{
	/// <summary>
	///	PromotionsFolder
	///	<para></para>
	///	<para>Path: /sitecore/templates/HedgehogDevelopment/Scaas/Models/PromotionsFolder</para>	
	///	<para>ID: 85930b65-5acb-412f-bba4-8afeef47c6ee</para>	
	///	<remarks>Generated by Team Development for Sitecore</remarks>
	///	</summary>
	public partial class PromotionsFolderItem : HedgehogDevelopment.Scaas.Content.ContentItem
	{
	
	}
}


namespace HedgehogDevelopment.Scaas.Models
{
	/// <summary>
	///	Article
	///	<para></para>
	///	<para>Path: /sitecore/templates/HedgehogDevelopment/Scaas/Models/Article</para>	
	///	<para>ID: a160af9b-4d3f-41a6-ab5a-cad61e67f119</para>	
	///	<remarks>Generated by Team Development for Sitecore</remarks>
	///	</summary>
	public partial class ArticleItem : HedgehogDevelopment.Scaas.Content.ContentItem
	{
		/// <summary>
		///	The ArticleCopy field.
		///	<para></para>
		///	<para>Field Type: Rich Text</para>		
		///	<para>Field ID: fc928cc8-3461-48ba-9383-0b9b7383888d</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public string ArticleCopy  {get; set;}

		/// <summary>
		///	The ArticleDate field.
		///	<para></para>
		///	<para>Field Type: Datetime</para>		
		///	<para>Field ID: f7ee3909-ce8c-4735-8cf9-4c1be51af898</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public DateTime ArticleDate  {get; set;}

		/// <summary>
		///	The ArticleImage field.
		///	<para></para>
		///	<para>Field Type: Image</para>		
		///	<para>Field ID: 864343d0-da30-4a80-8b28-5a27c41ebc6d</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public ImageField ArticleImage  {get; set;}

		/// <summary>
		///	The ArticleTitle field.
		///	<para></para>
		///	<para>Field Type: Single-Line Text</para>		
		///	<para>Field ID: eefd8188-8454-4d0a-9db1-438e5566a511</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public string ArticleTitle  {get; set;}

	
	}
}


namespace HedgehogDevelopment.Scaas.Models
{
	/// <summary>
	///	Content
	///	<para></para>
	///	<para>Path: /sitecore/templates/HedgehogDevelopment/Scaas/Models/Content</para>	
	///	<para>ID: c030f1ee-38ce-426e-8236-68cfea170aab</para>	
	///	<remarks>Generated by Team Development for Sitecore</remarks>
	///	</summary>
	public partial class ContentItem : HedgehogDevelopment.Scaas.Content.ContentItem
	{
		/// <summary>
		///	The ContentCopy field.
		///	<para></para>
		///	<para>Field Type: Rich Text</para>		
		///	<para>Field ID: dc4f6911-4027-4996-98e3-4d46696f6966</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public string ContentCopy  {get; set;}

		/// <summary>
		///	The ContentImage field.
		///	<para></para>
		///	<para>Field Type: Image</para>		
		///	<para>Field ID: 821946ae-4908-4b3b-8c43-9154bc01e1f7</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public ImageField ContentImage  {get; set;}

		/// <summary>
		///	The ContentTitle field.
		///	<para></para>
		///	<para>Field Type: Single-Line Text</para>		
		///	<para>Field ID: c0b01db1-69f2-4b6b-bf86-91745dc61b7b</para>
		///	<remarks>Generated by Team Development for Sitecore</remarks>
		/// </summary>
		public string ContentTitle  {get; set;}

	
	}
}


namespace HedgehogDevelopment.Scaas.Models
{
	/// <summary>
	///	Application
	///	<para></para>
	///	<para>Path: /sitecore/templates/HedgehogDevelopment/Scaas/Models/Application</para>	
	///	<para>ID: e14503a0-2823-4de1-bece-8a12782d28db</para>	
	///	<remarks>Generated by Team Development for Sitecore</remarks>
	///	</summary>
	public partial class ApplicationItem : HedgehogDevelopment.Scaas.Content.ContentItem
	{
	
	}
}
